[package]
org = "ballerinax"
name = "activemq"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["service", "client", "messaging", "network", "pubsub"]
repository = "https://github.com/ballerina-platform/module-ballerinax-activemq"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.10"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "activemq-native"
version = "@project.version@"
path = "../native/build/libs/activemq-native-@project.version@.jar"

[[platform.java21.dependency]]
groupId = "org.apache.activemq"
artifactId = "activemq-client"
version = "@activemq.version@"
path = "./lib/activemq-client-@activemq.version@.jar"

[[platform.java21.dependency]]
groupId = "jakarta.jms"
artifactId = "jakarta.jms-api"
version = "@jms.version@"
path = "./lib/jakarta.jms-api-@jms.version@.jar"

[[platform.java21.dependency]]
groupId = "org.fusesource.hawtbuf"
artifactId = "hawtbuf"
version = "@hawtbuf.version@"
path = "./lib/hawtbuf-@hawtbuf.version@.jar"
