[package]
org = "ballerinax"
name = "activemq"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["service", "client", "messaging", "network", "pubsub"]
repository = "https://github.com/ballerina-platform/module-ballerinax-activemq"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.10"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "activemq-native"
version = "0.1.0-SNAPSHOT"
path = "../native/build/libs/activemq-native-0.1.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "org.apache.activemq"
artifactId = "activemq-client"
version = "6.1.8"
path = "./lib/activemq-client-6.1.8.jar"

[[platform.java21.dependency]]
groupId = "jakarta.jms"
artifactId = "jakarta.jms-api"
version = "3.1.0"
path = "./lib/jakarta.jms-api-3.1.0.jar"

[[platform.java21.dependency]]
groupId = "org.fusesource.hawtbuf"
artifactId = "hawtbuf"
version = "1.11"
path = "./lib/hawtbuf-1.11.jar"
